name: Release

on:
  push:
    tags:
    - 'v*'

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-musl
          os: ubuntu-latest
          os_label: linux
          arch_label: amd64

        - target: aarch64-unknown-linux-musl
          os: ubuntu-latest
          os_label: linux
          arch_label: arm64

        - target: x86_64-apple-darwin
          os: macos-latest
          os_label: darwin
          arch_label: amd64

        - target: aarch64-apple-darwin
          os: macos-latest
          os_label: darwin
          arch_label: arm64

    runs-on: ${{ matrix.os }}
    env:
      ASSET_NAME: gh-ghq-cd_${{ github.ref_name }}_${{ matrix.os_label }}_${{ matrix.arch_label }}.tar.gz
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross [Linux]
      if: matrix.os == 'ubuntu-latest'
      uses: taiki-e/install-action@cross

    - name: Build [Cargo]
      if: matrix.os != 'ubuntu-latest'
      run: cargo build --release --locked --target ${{ matrix.target }}

    - name: Build [Cross]
      if: matrix.os == 'ubuntu-latest'
      run: cross build --release --locked --target ${{ matrix.target }}

    - name: Archive
      run: |
        cd target/${{ matrix.target }}/release
        tar czvf ../../../${{ env.ASSET_NAME }} gh-ghq-cd
        cd -

    - name: Upload artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.ASSET_NAME }}
        path: ${{ env.ASSET_NAME }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v6

    - name: Generate checksums
      run: |
        for file in gh-ghq-cd_*/gh-ghq-cd_*; do
          sha256sum "$file" | awk '{print $1}' > "${file}.sha256"
        done

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: gh-ghq-cd_*/gh-ghq-cd_*
        generate_release_notes: true
